######################################################################
#
# File name : OFDM_Tx_tb_wave.do
# Created on: Mon Mar 20 11:08:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_train/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_Modem/u_scram/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_Modem/u_conv/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_Modem/u_punt/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_Modem/u_intv/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_Modem/u_Qam16/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_Modem/u_pilot/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_ifft/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_cp_add/*
add wave -position insertpoint sim:/OFDM_Tx_tb/u_test/u_Trans_MCU/*