######################################################################
#
# File name : OFDM_Tx_tb_compile.do
# Created on: Fri Mar 24 12:35:53 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\intelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/work
D:\\intelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim

D:\\intelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim/xil_defaultlib

D:\\intelFPGA\\18.1\\modelsim_ase\\win32aloem\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\intelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../ofdm_new.gen/sources_1/ip/clk_wiz_0" \
"../../../../ofdm_new.gen/sources_1/ip/fifo_generator_1/sim/fifo_generator_1.v" \
"../../../../ofdm_new.gen/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \

D:\\intelFPGA\\18.1\\modelsim_ase\\win32aloem\\vcom  -93 -work xil_defaultlib  \
"../../../../ofdm_new.gen/sources_1/ip/xfft_0/sim/xfft_0.vhd" \

D:\\intelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../ofdm_new.gen/sources_1/ip/clk_wiz_0" \
"../../../../ofdm_new.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../ofdm_new.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../ofdm_Transmitter_file/IFFT.V" \
"../../../../ofdm_Transmitter_file/sequence_train/LTS_generator.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/OFDM_Data_Modem.v" \
"../../../../ofdm_Transmitter_file/sequence_train/STS_generator.v" \
"../../../../ofdm_Transmitter_file/Trans_MCU.v" \
"../../../../ofdm_Transmitter_file/cp_add.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/data_conv_code.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/data_interleaver.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/data_maping.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/data_pilot.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/data_puncturing.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/data_scramler.v" \
"../../../../ofdm_Transmitter_file/ofdm_tx_top.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/spram_128.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/spram_64.v" \
"../../../../ofdm_Transmitter_file/sequence_train/symbol_train.v" \
"../../../../ofdm_Transmitter_file/OFDM_Data_Modem/sync_buffer.v" \
"../../../../ofdm_Transmitter_file/tb/OFDM_Tx_tb.v" \

# compile glbl module
D:\\intelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog -work xil_defaultlib "glbl.v"

quit -force

